/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vincentramdhanie.twod.game;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appCreatesGamePanel() {
        // This is a very basic test just to verify the class exists
        App classUnderTest = new App();
        assertNotNull("app class should not be null", classUnderTest);
    }
}
